### ISSUE TITLE
Missing build artifact for the JSON highlighter

### ISSUE THREAD

**Issue by georgi-neykov-hub** [markusressel/KodeHighlighter#6]
Hello,

I'm interested in the JSON highlighter, but it seems it's missing from the Jitpack artifacts, you can see the build log there? There's something with the build configuration, maybe the json build artifact is missing from the Mavn pom file generated by the maven plugin you're using.

**Comment by markusressel** [comment]
The json highlighter was not part of the latest release yet. The README is a bit confusing because it is ahead of the latest release, sorry for that. Due to time constraints this project got a little out of my head and I am not sure what changed since 1.2.2. I will try to have a look and see if I can push a new release in the coming days if you are interested in that.

**Comment by georgi-neykov-hub** [comment]
All I needed was basic json highlighting, as a temporary solution I've
copied over the classes from the json module and they worked fine. It would
be great if you include the json in the next release. Thanks.

**Comment by markusressel** [comment]
The JSON highlighter is now included in the v2.0.0 release. Note there are many breaking changes too.
